name: GiveMeMoney
description: A sample web application  

dependencies:
  crypto: '>=0.9.0 <0.10.0'
  logging: '>=0.9.0 <0.10.0'
  options_file: '>=0.9.15'
  sqljocky: any
  async: any
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
